//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inspineaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecursosHumanosEntities : DbContext
    {
        public RecursosHumanosEntities()
            : base("name=RecursosHumanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbFaseSeleccion> tbFaseSeleccion { get; set; }
        public virtual DbSet<tbFasesReclutamiento> tbFasesReclutamiento { get; set; }
        public virtual DbSet<Prueba> Prueba { get; set; }
    
        public virtual ObjectResult<FasesReclutamiento_Result> FasesReclutamiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FasesReclutamiento_Result>("FasesReclutamiento");
        }
    }
}
