//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inspineaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebasEntities : DbContext
    {
        public PruebasEntities()
            : base("name=PruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }
    
        public virtual ObjectResult<string> UDP_Persona_Insert(Nullable<int> per_id, string per_nombre, string per_apellido, Nullable<int> per_edad)
        {
            var per_idParameter = per_id.HasValue ?
                new ObjectParameter("per_id", per_id) :
                new ObjectParameter("per_id", typeof(int));
    
            var per_nombreParameter = per_nombre != null ?
                new ObjectParameter("per_nombre", per_nombre) :
                new ObjectParameter("per_nombre", typeof(string));
    
            var per_apellidoParameter = per_apellido != null ?
                new ObjectParameter("per_apellido", per_apellido) :
                new ObjectParameter("per_apellido", typeof(string));
    
            var per_edadParameter = per_edad.HasValue ?
                new ObjectParameter("per_edad", per_edad) :
                new ObjectParameter("per_edad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Persona_Insert", per_idParameter, per_nombreParameter, per_apellidoParameter, per_edadParameter);
        }
    }
}
