//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inspineaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int per_id { get; set; }
        public string per_nombre { get; set; }
        public string per_apellido { get; set; }
        public Nullable<int> per_edad { get; set; }
    }
}
