//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inspineaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public int fsel_Id { get; set; }
        public string FasesReclutamiento { get; set; }
        public string DatosPrincipales { get; set; }
    }
}
